### ISSUE TITLE
feat(docs): add vuepress

### ISSUE THREAD

**Issue by vinayakkulkarni** [vinayakkulkarni/janak#39]
Add an option where users can create their own docs using VuePress

**Comment by elevatebart** [comment]
I have an example ready if you want with [vue-docgen-cli](https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-cli) & [vue-live](https://github.com/vue-styleguidist/vuepress-plugin-live)

It essentially generates a draft of your component documentation and allows you to see your components in action without lifting a finger.

I will make a PR.
