### ISSUE TITLE
Use lint-staged instead of full lint at every commit

### ISSUE THREAD

**Issue by elevatebart** [vinayakkulkarni/janak#41]
A commit on Janak takes about 20 seconds on my recent machine.
I only have about 200 components in but it is already a lot to work on.

Should I try and update Janak to use [lint-staged](https://github.com/okonet/lint-staged)?
- This only lints the files that are committed and prevent re-linting unchanged files.

**Comment by vinayakkulkarni** [comment]
yea that can be done :)

PR welcome :)

**Comment by vinayakkulkarni** [comment]
- [x] Done via https://github.com/vinayakkulkarni/janak/commit/3efc1dbd03f8aaed6cf64a3768a64e67c1b9ba12
